steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA', 
      '-t', 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:latest']

  # Deploy API Service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'site-monitoring-api-py'
      - '--image'
      - 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'PYTHON_ENV=production'
      - '--allow-unauthenticated'

  # Deploy Celery Worker to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'site-monitoring-worker-py'
      - '--image'
      - 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '3600'
      - '--no-cpu-throttling'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHON_ENV=production,ROLE=worker,CONCURRENCY=2'

  # Deploy Celery Beat to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'site-monitoring-beat-py'
      - '--image'
      - 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--set-env-vars'
      - 'PYTHON_ENV=production,ROLE=beat'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/site-monitoring-worker-py:latest'

# Substitution variables
substitutions:
  _REGION: 'us-central1'

# Build timeout
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
